### PR TITLE
Compile on OSX

### LINKED ISSUE #5: Compilation issue on macos
Compilation fails on OSX because of configuration for `node-gyp`

### PR DESCRIPTION
**Pull request by GaikwadPratik**
closes  #5

### CODE REVIEW

**Comment by GaikwadPratik** [comment]
@aironavt ,

I know this doesn't affect functionality or useful in another way than just letting the package compile/install on MacOS. Can you please merge the PR and release a new version?

**Comment by aironavt** [comment]
Please do not include package-lock.json in PR.

**Comment by GaikwadPratik** [comment]
May I know the reason for not including package-lock.json? the newer version on package-lock.json (v2) makes file dependency tree graph efficient and if we didn't commit then it would be out of sync with package.json for packages.

**Comment by aironavt** [comment]
The package with package-lock.json (v2) is not installed on NodeJS 8.
You can only include changes from the "bump version" commit.

**Pull request closed without merging**
